# src/main/resources/application.yml - UPDATED WITH APPOINTMENT CONFIGURATIONS

server:
  port: 8765
 

spring:
  application:
    name: edulink-pro
  
  data:
    mongodb:
      # --- FINAL CORRECTED URI ---
      # This now points to your Atlas cluster with the correct password.
      uri: mongodb+srv://ranawakaramr22:rothila2250@hacktivate.rq7koc2.mongodb.net/edulink?retryWrites=true&w=majority
      auto-index-creation: true
  
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  
  security:
    jwt:
      secret: ${JWT_SECRET:EduLinkProSecretKeyForJWTTokenGeneration2025HackVite}
      expiration: ${JWT_EXPIRATION:86400000} # 24 hours
      refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days

  # --- NEW: Task Scheduling Configuration ---
  task:
    scheduling:
      enabled: true
      pool:
        size: 10
    execution:
      pool:
        core-size: 5
        max-size: 50
        queue-capacity: 100

# CORS Configuration
cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:3001}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# --- NEW: Appointment System Configuration ---
appointment:
  # Recurring appointment settings
  recurring:
    enabled: true
    max-instances: 52 # Maximum instances to create for recurring appointments (1 year weekly)
    cleanup-enabled: true
    cleanup-cron: "0 0 2 * * ?" # Daily at 2 AM
    
  # Automatic status updates
  auto-status-update:
    enabled: true
    mark-past-as-completed: false # Don't auto-complete, let lecturers mark manually
    mark-no-show-after-minutes: 30 # Mark as no-show if 30 minutes past scheduled time
    cleanup-old-appointments: true
    keep-completed-days: 365 # Keep completed appointments for 1 year
    keep-cancelled-days: 90 # Keep cancelled appointments for 3 months
    
  # Notification settings
  notifications:
    enabled: true
    email-enabled: ${APPOINTMENT_EMAIL_NOTIFICATIONS:false} # Disabled by default
    reminder-minutes: [1440, 60, 15] # Send reminders 1 day, 1 hour, and 15 minutes before
    
  # Business rules
  business-rules:
    min-booking-advance-hours: 2 # Must book at least 2 hours in advance
    max-booking-advance-days: 30 # Can't book more than 30 days in advance
    max-duration-minutes: 180 # Maximum 3 hours per appointment
    min-duration-minutes: 15 # Minimum 15 minutes per appointment
    cancel-deadline-hours: 2 # Must cancel at least 2 hours before
    
  # Time slot generation settings
  time-slots:
    default-duration-minutes: 30
    default-start-hour: 9 # 9 AM
    default-end-hour: 17 # 5 PM
    interval-minutes: 30 # 30-minute intervals
    weekend-enabled: false # Don't generate weekend slots by default
    
  # Conflict detection
  conflict-detection:
    enabled: true
    buffer-minutes: 0 # No buffer time between appointments by default
    allow-back-to-back: true

# --- NEW: Email Configuration (for appointment notifications) ---
mail:
  enabled: ${MAIL_ENABLED:false}
  smtp:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    auth: true
    starttls:
      enable: true
  from:
    address: ${MAIL_FROM_ADDRESS:noreply@edulink.com}
    name: ${MAIL_FROM_NAME:EduLink System}
  templates:
    appointment-confirmation: "appointment-confirmation"
    appointment-reminder: "appointment-reminder"
    appointment-cancellation: "appointment-cancellation"
    appointment-rescheduled: "appointment-rescheduled"

# Logging
logging:
  level:
    com.edulink: ${LOG_LEVEL:DEBUG}
    org.springframework.data.mongodb: DEBUG
    org.springframework.security: DEBUG
    org.springframework.scheduling: INFO # Add scheduling logs
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints for health check
management:
  endpoints:
    web:
      exposure:
        include: health,info,scheduledtasks # Add scheduled tasks endpoint
  endpoint:
    health:
      show-details: always
    scheduledtasks:
      enabled: true

# --- NEW: Performance and Caching Configuration ---
cache:
  appointment-stats:
    ttl-minutes: 15 # Cache appointment stats for 15 minutes
  available-slots:
    ttl-minutes: 5 # Cache available slots for 5 minutes
  lecturer-availability:
    ttl-minutes: 30 # Cache lecturer availability for 30 minutes

# --- NEW: Rate Limiting (if needed) ---
rate-limit:
  appointment-booking:
    requests-per-minute: 10 # Max 10 appointment bookings per minute per user
  slot-queries:
    requests-per-minute: 30 # Max 30 slot queries per minute per user

# --- NEW: Feature Flags ---
features:
  recurring-appointments: ${FEATURE_RECURRING_APPOINTMENTS:true}
  appointment-attachments: ${FEATURE_APPOINTMENT_ATTACHMENTS:true}
  video-meetings: ${FEATURE_VIDEO_MEETINGS:true}
  automatic-calendar-sync: ${FEATURE_CALENDAR_SYNC:false}
  appointment-analytics: ${FEATURE_APPOINTMENT_ANALYTICS:true}
  smart-scheduling: ${FEATURE_SMART_SCHEDULING:false} # AI-powered scheduling suggestions

# --- NEW: Integration Settings ---
integrations:
  zoom:
    enabled: ${ZOOM_INTEGRATION_ENABLED:false}
    api-key: ${ZOOM_API_KEY:}
    api-secret: ${ZOOM_API_SECRET:}
    
  google-calendar:
    enabled: ${GOOGLE_CALENDAR_ENABLED:false}
    client-id: ${GOOGLE_CLIENT_ID:}
    client-secret: ${GOOGLE_CLIENT_SECRET:}
    
  microsoft-teams:
    enabled: ${TEAMS_INTEGRATION_ENABLED:false}
    client-id: ${TEAMS_CLIENT_ID:}
    client-secret: ${TEAMS_CLIENT_SECRET:}

# --- NEW: Database Indexing Hints ---
mongodb:
  indexes:
    appointment:
      # These will be created automatically by the application
      - fields: { studentId: 1, scheduledAt: -1 }
      - fields: { lecturerId: 1, scheduledAt: -1 }
      - fields: { status: 1, scheduledAt: 1 }
      - fields: { scheduledAt: 1, status: 1 }
      - fields: { parentAppointmentId: 1 }
      - fields: { courseId: 1, scheduledAt: -1 }
      - fields: { isRecurring: 1, scheduledAt: 1 }

# --- NEW: Monitoring and Metrics ---
metrics:
  appointment:
    track-booking-success-rate: true
    track-no-show-rate: true
    track-cancellation-rate: true
    track-average-duration: true
    track-popular-time-slots: true