# src/main/resources/application.yml - PRODUCTION READY VERSION

server:
  port: ${PORT:8765}

spring:
  application:
    name: edulink-pro
  
  data:
    mongodb:
      # MongoDB Atlas URI
      uri: mongodb+srv://ranawakaramr22:rothila2250@hacktivate.rq7koc2.mongodb.net/edulink?retryWrites=true&w=majority
      auto-index-creation: true
  
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  
  security:
    jwt:
      secret: ${JWT_SECRET:EduLinkProSecretKeyForJWTTokenGeneration2025HackVite}
      expiration: ${JWT_EXPIRATION:86400000} # 24 hours
      refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days

  # Task Scheduling Configuration
  task:
    scheduling:
      enabled: true
      pool:
        size: 10
    execution:
      pool:
        core-size: 5
        max-size: 50
        queue-capacity: 100

# CORS Configuration - Now environment variable driven
cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:3001}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Appointment System Configuration
appointment:
  # Recurring appointment settings
  recurring:
    enabled: true
    max-instances: 52
    cleanup-enabled: true
    cleanup-cron: "0 0 2 * * ?"
    
  # Automatic status updates
  auto-status-update:
    enabled: true
    mark-past-as-completed: false
    mark-no-show-after-minutes: 30
    cleanup-old-appointments: true
    keep-completed-days: 365
    keep-cancelled-days: 90
    
  # Notification settings
  notifications:
    enabled: true
    email-enabled: ${APPOINTMENT_EMAIL_NOTIFICATIONS:false}
    reminder-minutes: [1440, 60, 15]
    
  # Business rules
  business-rules:
    min-booking-advance-hours: 2
    max-booking-advance-days: 30
    max-duration-minutes: 180
    min-duration-minutes: 15
    cancel-deadline-hours: 2
    
  # Time slot generation settings
  time-slots:
    default-duration-minutes: 30
    default-start-hour: 9
    default-end-hour: 17
    interval-minutes: 30
    weekend-enabled: false
    
  # Conflict detection
  conflict-detection:
    enabled: true
    buffer-minutes: 0
    allow-back-to-back: true

# Email Configuration
mail:
  enabled: ${MAIL_ENABLED:false}
  smtp:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    auth: true
    starttls:
      enable: true
  from:
    address: ${MAIL_FROM_ADDRESS:noreply@edulink.com}
    name: ${MAIL_FROM_NAME:EduLink System}
  templates:
    appointment-confirmation: "appointment-confirmation"
    appointment-reminder: "appointment-reminder"
    appointment-cancellation: "appointment-cancellation"
    appointment-rescheduled: "appointment-rescheduled"

# Logging
logging:
  level:
    com.edulink: ${LOG_LEVEL:INFO}
    org.springframework.data.mongodb: ${LOG_LEVEL:INFO}
    org.springframework.security: ${LOG_LEVEL:INFO}
    org.springframework.scheduling: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints for health check
management:
  endpoints:
    web:
      exposure:
        include: health,info,scheduledtasks
  endpoint:
    health:
      show-details: always
    scheduledtasks:
      enabled: true

# Performance and Caching Configuration
cache:
  appointment-stats:
    ttl-minutes: 15
  available-slots:
    ttl-minutes: 5
  lecturer-availability:
    ttl-minutes: 30

# Rate Limiting
rate-limit:
  appointment-booking:
    requests-per-minute: 10
  slot-queries:
    requests-per-minute: 30

# Feature Flags
features:
  recurring-appointments: ${FEATURE_RECURRING_APPOINTMENTS:true}
  appointment-attachments: ${FEATURE_APPOINTMENT_ATTACHMENTS:true}
  video-meetings: ${FEATURE_VIDEO_MEETINGS:true}
  automatic-calendar-sync: ${FEATURE_CALENDAR_SYNC:false}
  appointment-analytics: ${FEATURE_APPOINTMENT_ANALYTICS:true}
  smart-scheduling: ${FEATURE_SMART_SCHEDULING:false}

# Integration Settings
integrations:
  zoom:
    enabled: ${ZOOM_INTEGRATION_ENABLED:false}
    api-key: ${ZOOM_API_KEY:}
    api-secret: ${ZOOM_API_SECRET:}
    
  google-calendar:
    enabled: ${GOOGLE_CALENDAR_ENABLED:false}
    client-id: ${GOOGLE_CLIENT_ID:}
    client-secret: ${GOOGLE_CLIENT_SECRET:}
    
  microsoft-teams:
    enabled: ${TEAMS_INTEGRATION_ENABLED:false}
    client-id: ${TEAMS_CLIENT_ID:}
    client-secret: ${TEAMS_CLIENT_SECRET:}

# Database Indexing Hints
mongodb:
  indexes:
    appointment:
      - fields: { studentId: 1, scheduledAt: -1 }
      - fields: { lecturerId: 1, scheduledAt: -1 }
      - fields: { status: 1, scheduledAt: 1 }
      - fields: { scheduledAt: 1, status: 1 }
      - fields: { parentAppointmentId: 1 }
      - fields: { courseId: 1, scheduledAt: -1 }
      - fields: { isRecurring: 1, scheduledAt: 1 }

# Monitoring and Metrics
metrics:
  appointment:
    track-booking-success-rate: true
    track-no-show-rate: true
    track-cancellation-rate: true
    track-average-duration: true
    track-popular-time-slots: true